// Generates src/font.css with the Bangers display font embedded as a
// base64 data URI. This keeps the font fully self-hosted (offline PWA
// still works) while emitting NO .woff/.woff2 files into the build —
// some upload targets reject those extensions.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
// latin subset only — the UI is English, so the ext/vietnamese cuts are dead weight
const src = join(root, 'node_modules', '@fontsource', 'bangers', 'files', 'bangers-latin-400-normal.woff2');
const out = join(root, 'src', 'font.css');

const b64 = readFileSync(src).toString('base64');
const css = `/* GENERATED by scripts/gen-font.mjs — do not edit by hand. */
@font-face {
  font-family: 'Bangers';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(data:font/woff2;base64,${b64}) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
`;
writeFileSync(out, css);
console.log(`font: inlined ${(b64.length / 1024).toFixed(1)} kB base64 -> src/font.css`);
